version: '3'
services:
  pacs_provider:
    image: floymedical/pacs_technical_challenge:latest
    environment:
      DEFAULT_USER: orthanc
      PASS: orthanc
    ports:
      - "4242:4242"
      - "6667:6667"
      - "8042:8042"

  automation:
    build:
      context: ./
      dockerfile: src/automation_orthanc/Dockerfile
    depends_on:
      - pacs_provider
    links:
      - pacs_provider
    container_name: floy_automation
    volumes:
      - ./src:/floy/src
      - ./sample_data:/floy/sample_data
    environment:
      - HEADLESS=true
      - PACS_PROVIDER_HOST=pacs_provider
      - PACS_PROVIDER_PORT=8042
    command: bash -c "python3 -m src.automation_orthanc.fill_pacs"
