"""Created received_data table

Revision ID: f02f2cfaffda
Revises:
Create Date: 2024-01-02 03:45:13.663539

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f02f2cfaffda"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "received_data",
        sa.Column(
            "patient_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "patient_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "study_instance_uid",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("instances_in_series", sa.Integer(), nullable=False),
        sa.Column(
            "series_instance_uid",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("series_instance_uid"),
    )
    op.create_index(
        op.f("ix_received_data_patient_id"),
        "received_data",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_received_data_study_instance_uid"),
        "received_data",
        ["study_instance_uid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_received_data_study_instance_uid"), table_name="received_data"
    )
    op.drop_index(
        op.f("ix_received_data_patient_id"), table_name="received_data"
    )
    op.drop_table("received_data")
    # ### end Alembic commands ###
